# Generated by Django 5.1.5 on 2025-02-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('language_code', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('last_activity', models.DateField(auto_now_add=True)),
                ('notifications', models.BooleanField()),
            ],
        ),
    ]
