# Generated by Django 5.1.5 on 2025-02-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='start_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='category',
            field=models.CharField(default='nocategory', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='color',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='icon',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='notifications',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='paymentDate',
            field=models.DateField(default='2025-10-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='period',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='periodType',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
