# Generated by Django 5.1.5 on 2025-02-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscription_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='color',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='notifications',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='paymentDate',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='period',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='periodType',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user_id',
        ),
    ]
