# Generated by Django 5.1.5 on 2025-03-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscription_category_subscription_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_notification',
            field=models.DateField(blank=True, null=True),
        ),
    ]
